// sync-schema.mjs - generates src/generated/schema.ts from the canonical
// SQLite schema in internal/storage/schema.go.
//
// The TeslaMate importer builds a teslalog database in the browser, so it
// needs the same schema the daemon writes. That schema used to be
// hand-copied into teslamateImport.ts, and it drifted: geocode_cache was
// missing entirely - so an imported database had no address data and the
// Locations dashboard failed on it - along with two positions columns
// added later. Nothing detected any of that.
//
// Go stays the source of truth because that is what actually writes the
// live database. Both the CREATE TABLE block and the ADD COLUMN
// migrations are read, since columns added after the first release live
// only in the migration list.
import { readFile, mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const frontend = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repo = resolve(frontend, '..')

const schemaGo = await readFile(resolve(repo, 'internal/storage/schema.go'), 'utf8')
const storageGo = await readFile(resolve(repo, 'internal/storage/storage.go'), 'utf8')

const block = schemaGo.match(/const schema = `([\s\S]*?)\n`/)
if (!block) throw new Error('Could not find `const schema = ` in internal/storage/schema.go')

// Comments are stripped: they explain the daemon's behaviour and are long
// enough to dominate the generated file, where they would be read as
// documentation of the importer instead.
const statements = block[1]
  .split('\n')
  .filter((line) => !line.trimStart().startsWith('--'))
  .join('\n')
  .split(';')
  .map((statement) => statement.trim())
  .filter(Boolean)
  // PRAGMA foreign_keys is the daemon's concern. The importer assigns ids
  // from the dump and inserts tables in whatever order the dump lists
  // them, so enforcing keys mid-import would reject valid rows.
  .filter((statement) => !/^PRAGMA/i.test(statement))
  .map((statement) => statement.replace(/[ \t]+/g, ' ').replace(/\n /g, '\n'))

const migrations = [...storageGo.matchAll(/`(ALTER TABLE [^`]+)`/g)].map((match) =>
  match[1].replace(/\s+/g, ' ').trim(),
)
if (migrations.length === 0) throw new Error('Found no ALTER TABLE migrations in storage.go')

const output = `// GENERATED by scripts/sync-schema.mjs - do not edit.
//
// The canonical SQLite schema, extracted from internal/storage/schema.go
// and the ADD COLUMN migrations in internal/storage/storage.go. Run
// \`npm run sync:schema\` after changing either.
//
// Regenerating rather than hand-copying is deliberate: the copy that used
// to live in teslamateImport.ts drifted, losing the whole geocode_cache
// table and two positions columns, which produced imported databases that
// silently failed the Locations dashboard.

/** CREATE TABLE / CREATE INDEX statements, in dependency order. */
export const schemaStatements: readonly string[] = [
${statements.map((s) => `  \`${s}\`,`).join('\n')}
]

/**
 * ADD COLUMN migrations for columns introduced after a table's first
 * release. Applied after schemaStatements; each may already exist, which
 * is not an error.
 */
export const columnMigrations: readonly string[] = [
${migrations.map((s) => `  '${s}',`).join('\n')}
]

/** Every table the schema defines. */
export const schemaTables: readonly string[] = [
${[...new Set(statements.flatMap((s) => s.match(/CREATE TABLE (?:IF NOT EXISTS )?(\w+)/)?.slice(1, 2) ?? []))]
  .map((t) => `  '${t}',`)
  .join('\n')}
]
`

const outputPath = resolve(frontend, 'src/generated/schema.ts')
await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, output, 'utf8')
console.log(
  `Generated ${statements.length} statements and ${migrations.length} migrations at ${outputPath}`,
)
