CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT PRIMARY KEY, vin TEXT UNIQUE, tesla_id TEXT, display_name TEXT,
  model TEXT, trim_badging TEXT, marketing_name TEXT, exterior_color TEXT,
  wheel_type TEXT, spoiler_type TEXT, efficiency_wh_km REAL,
  created_at TEXT, firmware_version TEXT
);
CREATE TABLE IF NOT EXISTS geofences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE,
  latitude REAL, longitude REAL, radius_m REAL,
  billing_type TEXT DEFAULT 'per_kwh', cost_per_unit REAL, session_fee REAL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS geocode_cache (
  lat_key REAL NOT NULL, lng_key REAL NOT NULL, name TEXT, created_at TEXT,
  road TEXT, city TEXT, county TEXT, state TEXT, postcode TEXT, country TEXT,
  PRIMARY KEY (lat_key,lng_key)
);
CREATE TABLE IF NOT EXISTS states (
  id BIGINT PRIMARY KEY, vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  state TEXT, started_at TEXT, ended_at TEXT
);
CREATE TABLE IF NOT EXISTS drives (
  id BIGINT PRIMARY KEY, vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  start_time TEXT, end_time TEXT, start_odometer_km REAL, end_odometer_km REAL,
  distance_km REAL, duration_min REAL, start_battery_level BIGINT, end_battery_level BIGINT,
  start_range_km REAL, end_range_km REAL, start_ideal_range_km REAL, end_ideal_range_km REAL,
  start_lat REAL, start_lng REAL, end_lat REAL, end_lng REAL, max_speed_kmh REAL,
  max_power_kw REAL, min_power_kw REAL, outside_temp_avg_c REAL, inside_temp_avg_c REAL,
  ascent_m REAL, descent_m REAL, status TEXT DEFAULT 'open', start_location TEXT, end_location TEXT
);
CREATE TABLE IF NOT EXISTS positions (
  id BIGINT PRIMARY KEY, drive_id BIGINT REFERENCES drives(id) ON DELETE CASCADE,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE, "timestamp" TEXT,
  latitude REAL, longitude REAL, speed_kmh REAL, heading REAL, elevation_m REAL,
  power_kw REAL, odometer_km REAL, battery_level BIGINT, usable_battery_level BIGINT,
  range_km REAL, ideal_range_km REAL, est_range_km REAL, battery_heater_on BIGINT,
  outside_temp_c REAL, inside_temp_c REAL, fan_status BIGINT, driver_temp_setting_c REAL,
  passenger_temp_setting_c REAL, is_climate_on BIGINT, is_rear_defroster_on BIGINT,
  is_front_defroster_on BIGINT, tpms_pressure_fl REAL, tpms_pressure_fr REAL,
  tpms_pressure_rl REAL, tpms_pressure_rr REAL, shift_state TEXT, sentry_mode BIGINT,
  is_user_present BIGINT, valet_mode BIGINT, climate_keeper_mode TEXT,
  battery_heater BIGINT, battery_heater_no_power BIGINT
);
CREATE TABLE IF NOT EXISTS charging_sessions (
  id BIGINT PRIMARY KEY, vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  geofence_id BIGINT REFERENCES geofences(id) ON DELETE SET NULL,
  start_time TEXT, end_time TEXT, start_battery_level BIGINT, end_battery_level BIGINT,
  start_range_km REAL, end_range_km REAL, start_ideal_range_km REAL, end_ideal_range_km REAL,
  charge_energy_added_kwh REAL, charge_energy_used_kwh REAL, max_charger_power_kw REAL,
  outside_temp_avg_c REAL, cost REAL, latitude REAL, longitude REAL,
  status TEXT DEFAULT 'open', location TEXT, is_dc_fast_charge BIGINT
);
ALTER TABLE charging_sessions ADD COLUMN IF NOT EXISTS geofence_id BIGINT REFERENCES geofences(id) ON DELETE SET NULL;
CREATE TABLE IF NOT EXISTS charging_samples (
  id BIGINT PRIMARY KEY, charging_session_id BIGINT REFERENCES charging_sessions(id) ON DELETE CASCADE,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE, "timestamp" TEXT,
  battery_level BIGINT, usable_battery_level BIGINT, charger_power_kw REAL,
  charger_voltage REAL, charger_actual_current REAL, charger_pilot_current BIGINT,
  charger_phases BIGINT, conn_charge_cable TEXT, fast_charger_present BIGINT,
  fast_charger_brand TEXT, fast_charger_type TEXT, charge_energy_added_kwh REAL,
  range_km REAL, ideal_range_km REAL, battery_heater_on BIGINT,
  not_enough_power_to_heat BIGINT, outside_temp_c REAL, charge_limit_soc BIGINT
);
CREATE TABLE IF NOT EXISTS battery_samples (
  id BIGINT PRIMARY KEY, vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  "timestamp" TEXT, battery_level BIGINT, battery_range_km REAL,
  ideal_battery_range_km REAL, source TEXT
);
CREATE TABLE IF NOT EXISTS software_updates (
  id BIGINT PRIMARY KEY, vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  version TEXT, status TEXT, start_time TEXT, end_time TEXT
);
CREATE TABLE IF NOT EXISTS teslalog_replication_meta (
  name TEXT PRIMARY KEY, completed_at TEXT NOT NULL
);

CREATE OR REPLACE FUNCTION teslalog_advance_geofence_id() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('geofences','id'),
    GREATEST(NEW.id, COALESCE((SELECT MAX(id) FROM geofences),1)), true);
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS teslalog_geofence_id_sequence ON geofences;
CREATE TRIGGER teslalog_geofence_id_sequence AFTER INSERT ON geofences
FOR EACH ROW EXECUTE FUNCTION teslalog_advance_geofence_id();

CREATE INDEX IF NOT EXISTS idx_states_vehicle_started ON states(vehicle_id,started_at);
CREATE INDEX IF NOT EXISTS idx_states_open ON states(vehicle_id,ended_at);
CREATE INDEX IF NOT EXISTS idx_drives_vehicle_start ON drives(vehicle_id,start_time);
CREATE INDEX IF NOT EXISTS idx_drives_status ON drives(vehicle_id,status);
CREATE INDEX IF NOT EXISTS idx_positions_drive ON positions(drive_id,"timestamp");
CREATE INDEX IF NOT EXISTS idx_charging_sessions_vehicle_start ON charging_sessions(vehicle_id,start_time);
CREATE INDEX IF NOT EXISTS idx_charging_sessions_status ON charging_sessions(vehicle_id,status);
CREATE INDEX IF NOT EXISTS idx_charging_samples_session ON charging_samples(charging_session_id,"timestamp");
CREATE INDEX IF NOT EXISTS idx_battery_samples_vehicle_ts ON battery_samples(vehicle_id,"timestamp");
CREATE INDEX IF NOT EXISTS idx_battery_samples_timestamp ON battery_samples("timestamp");
CREATE INDEX IF NOT EXISTS idx_software_updates_vehicle ON software_updates(vehicle_id,start_time);

CREATE OR REPLACE FUNCTION julianday(value TEXT) RETURNS DOUBLE PRECISION
LANGUAGE SQL IMMUTABLE PARALLEL SAFE AS $$
  SELECT EXTRACT(EPOCH FROM value::timestamptz) / 86400.0 + 2440587.5
$$;
CREATE OR REPLACE FUNCTION datetime(value TEXT, modifier TEXT DEFAULT NULL) RETURNS TEXT
LANGUAGE plpgsql STABLE AS $$
DECLARE result timestamptz;
BEGIN
  result := CASE WHEN lower(value) = 'now' THEN now() ELSE value::timestamptz END;
  IF modifier IS NOT NULL THEN result := result + modifier::interval; END IF;
  RETURN to_char(result AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');
END $$;
CREATE OR REPLACE FUNCTION strftime(format TEXT, value TEXT) RETURNS TEXT
LANGUAGE SQL STABLE AS $$
  SELECT to_char(value::timestamptz AT TIME ZONE 'UTC',
    CASE format WHEN '%Y-%m-%dT%H:00:00Z' THEN 'YYYY-MM-DD"T"HH24:00:00"Z"'
                WHEN '%Y-%m-%d' THEN 'YYYY-MM-DD'
                WHEN '%Y-%m' THEN 'YYYY-MM'
                WHEN '%H' THEN 'HH24'
                ELSE 'YYYY-MM-DD HH24:MI:SS' END)
$$;
CREATE OR REPLACE FUNCTION printf(format TEXT, a DOUBLE PRECISION, b DOUBLE PRECISION) RETURNS TEXT
LANGUAGE SQL IMMUTABLE PARALLEL SAFE AS $$ SELECT to_char(a,'FM999999990.0000') || ', ' || to_char(b,'FM999999990.0000') $$;
CREATE OR REPLACE FUNCTION round(value DOUBLE PRECISION, digits INTEGER) RETURNS NUMERIC
LANGUAGE SQL IMMUTABLE PARALLEL SAFE AS $$ SELECT pg_catalog.round(value::numeric,digits) $$;
CREATE OR REPLACE FUNCTION max(a DOUBLE PRECISION,b DOUBLE PRECISION) RETURNS DOUBLE PRECISION
LANGUAGE SQL IMMUTABLE PARALLEL SAFE AS $$ SELECT greatest(a,b) $$;
CREATE OR REPLACE FUNCTION min(a DOUBLE PRECISION,b DOUBLE PRECISION) RETURNS DOUBLE PRECISION
LANGUAGE SQL IMMUTABLE PARALLEL SAFE AS $$ SELECT least(a,b) $$;
